name: eventtt_app
description: "EVENT ITT - Luxury Wedding Venue & Planning App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  video_player: ^2.9.2
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.0+1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/



